## This is test deployment for Kubernetes platforms.
## This is _not_ intended to be used in production.
##
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: test-configmap-reload
    app.kubernetes.io/component: configmap-reload
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: test-configmap-reload
      app.kubernetes.io/component: configmap-reload
  template:
    metadata:
      labels:
        app.kubernetes.io/name: test-configmap-reload
        app.kubernetes.io/component: configmap-reload
    spec:
      containers:
      - image: bitnami/configmap-reload
        name: configmap-reload
        #env:
        #- name: BITNAMI_DEBUG
        #- value: 0
        ports:
        - name: configmap-reload-port-8080
          containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: test-configmap-reload
  labels:
    app.kubernetes.io/name: test-configmap-reload
    app.kubernetes.io/component: configmap-reload
spec:
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
    targetPort: configmap-reload-port-8080
  selector:
    app.kubernetes.io/name: test-configmap-reload
    app.kubernetes.io/component: configmap-reload
